In [ ]:
print("hello I'm excited to learn Pytorch")

hello I'm excited to learn Pytorch


In [ ]:
!nvidia-smi #to check gpu specification

Tue May 21 05:34:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121



## Introduction to Tensors

#### Creating Tensors

## 1. Scaler

In [ ]:
# Pytorch tensors are created using torch.Tensors()

scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item()  ## Get tensor back as Python int

7

## 2. Vector

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # can be understand as no of square brackets

1

In [ ]:
vector.shape  # no of row and column

torch.Size([2])

## 3. MATRIX

In [ ]:
MATRIX = torch.tensor([
    [7,8],
    [9,10],
    [11,12]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([3, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[1:2]

tensor([[ 9, 10]])

##  4. TENSOR

In [ ]:
TENSOR = torch.tensor(
    [[
        [1,2,3],
        [3,6,9],
        [2,4,5]
    ]]
)

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

## 5. Random Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random number and then adjust those random number to better represent the data

``` Start with random number -> look at data -> update random numbers -> look at data -> update random numbers ```

In [ ]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7294, 0.7152, 0.1416, 0.6951],
        [0.3029, 0.7630, 0.5621, 0.4954],
        [0.3339, 0.4958, 0.5468, 0.0967]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor1 = torch.rand(1,5,6)   # 1 matrix of 5 * 6

In [ ]:
random_tensor1

tensor([[[0.2487, 0.8768, 0.7041, 0.5055, 0.7221, 0.2452],
         [0.5935, 0.1856, 0.3761, 0.4084, 0.6509, 0.4970],
         [0.7719, 0.3584, 0.6656, 0.3064, 0.7740, 0.0613],
         [0.0850, 0.2337, 0.0320, 0.1559, 0.1046, 0.6054],
         [0.3788, 0.0199, 0.9388, 0.4010, 0.2478, 0.4413]]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
# random_image_size_tensor1 = torch.rand(3,224,224)
random_image_size_tensor = torch.rand(size=(3,224,224)) # color channels (R, G, B), height, width

In [ ]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## 6. Zeros and ones

In [ ]:
 # create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## 6. Range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten= torch.arange(0,10)
one_to_hundered_even = torch.arange(start=2,end=100,step=2)

one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_hundered_even

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
        38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72,
        74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
# creating tensor like meaning of the same size

ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 7. Tensor datatypes


**Note:** Tensor datatypes is one of the 3 big error you'll run into with pytorch and deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device



In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype =torch.float32, # what data type tensor is eg.(float16, float32)
                               device = None,  # device = "cpu" or device = "cuda "
                               requires_grad = False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

## 8. Getting information from tensors(tensor attributes)

1. Tensors datatype (tensor.dtype)
2. Tensors device   (tensor.shape)
3. Tensors shape    (tensor.device)

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5117, 0.8298, 0.6521, 0.6887],
        [0.1166, 0.7052, 0.0822, 0.5811],
        [0.9416, 0.0731, 0.3852, 0.9574]])

In [ ]:
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape/Size of tensor:{some_tensor.shape}")
print(f"Device tensor is on {some_tensor.device}")

Datatype of tensor:torch.float32
Shape/Size of tensor:torch.Size([3, 4])
Device tensor is on cpu


## 9. Manipulating Tensors (tensor operations)

 Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,3,5])
tensor + 10

tensor([11, 13, 15])

In [ ]:
# Multiply tensor by 10
tensor*10

tensor([10, 30, 50])

In [ ]:
# divide tensor by 10
tensor/10

tensor([0.1000, 0.3000, 0.5000])

In [ ]:
# subtract tensor by 10
tensor - 10

tensor([-9, -7, -5])

In [ ]:
## Try out pytorch inbuilt function
torch.mul(tensor, 10)

tensor([10, 30, 50])

In [ ]:
torch.div(tensor,10)

tensor([0.1000, 0.3000, 0.5000])

In [ ]:
torch.add(tensor,10)

tensor([11, 13, 15])

In [ ]:
torch.sub(tensor,2)

tensor([-1,  1,  3])

## 10. Matrix Multiplication (dot product)

Rules
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work 2,2
2. The Resulting matrix has the shape of the **outer dimeneions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
tensor

tensor([1, 3, 5])

In [ ]:
torch.matmul(tensor, tensor)

tensor(35)

In [ ]:
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6],
])

tensor_B = torch.tensor([
    [7,8],
    [9,10],
    [11,12]
])

torch.mm(tensor_A,tensor_B) # mm = matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.T ##

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
torch.mm(tensor_A.T ,tensor_B)

tensor([[ 89,  98],
        [116, 128]])

## 11. Aggregation Function (min,max,avg)

In [ ]:
x = torch.arange(0,100,10)

In [ ]:
# finding minimum tensor
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
# finding max tensor
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
# findin average
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

## 12. **argmin** : (position of tensor with min value)
## **argmmax** : (position of tensor with max value)

In [ ]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

## 13. Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack)  or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimension permuted(swapped) in a certain way means it share value with original tensor

In [ ]:
# Let's create a tensors
import torch
x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stacking tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() remove 1 dimension

x_reshaped = x_reshaped.reshape(1,9)

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed = x.squeeze()

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target at a specific dim

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with squeeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224,224,3)) # [height,width, color channels]

# Permute the original tensor to rearrange the axis (or dim)
x_permuted = x_original.permute(2,0,1)  # shift axis 0 ->1 , 1->2, 2->0

print(f"Previous Shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous Shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## 14. Indexing (selecting data from tensors with indexing).

indexing in pytorch is same as numpy indexing

In [4]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [5]:
# Let's index on out new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
# Let's index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [7]:
# let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [8]:
x[0][2][2]

tensor(9)

In [9]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [10]:
# Get all value of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [11]:
# get all value of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [12]:
# Get index 0 of 0th and 1st dimension and all value of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## 15. Pytorch tensors & Numpy

Numpy is popular scientific Python numerical computing library

And Because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [18]:
# Numpy array to tensor
import torch   # default datatype = float32
import numpy as np

array = np.arange(1.0,8.0) # default datatype = float 64
tensor = torch.from_numpy(array).type(torch.float32) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [19]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [20]:
# Change the value of array, what will this do to `tensor` ?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [28]:
# Tensor to numpy array
tensor = torch.ones(2,2,3)
new_array = tensor.numpy()
new_array, new_array.dtype # float 32 because default data type of torch is float32

(array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32),
 dtype('float32'))

In [30]:
# change the tensor, what happens to `numpy_tensor` ?
tensor = tensor+1
tensor, new_array # means doesn't share memory

(tensor([[[3., 3., 3.],
          [3., 3., 3.]],
 
         [[3., 3., 3.],
          [3., 3., 3.]]]),
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32))

## 16. Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operation -> update random numbers to try and make them better representation of the data -> again -> again -> again ...`


To reduce the randomness in neural networks and Pytorch comes the concept of **random seed**.

Essentially what the random seed does is "flavour" the randomness

In [34]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2408, 0.0622, 0.8239, 0.5339],
        [0.3740, 0.7196, 0.6226, 0.0923],
        [0.0898, 0.9756, 0.2748, 0.1761]])
tensor([[0.6078, 0.8681, 0.6500, 0.5291],
        [0.6826, 0.4989, 0.7280, 0.3023],
        [0.3171, 0.7973, 0.5820, 0.0418]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [36]:
# Let's make some radom but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## 17. Running tensors on GPU

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory(good).

### 1. Getting a GPU
1. Easiest - Use Googe Colab for a free GPU (options to upgrade as well)

2. Use your on GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..

3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and acess them


for 2, 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refers to PyTorch setup documentation:


In [42]:
!nvidia-smi

Mon May 27 08:00:25 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   29C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check GPU access with PyTorch

In [8]:
import torch
# Chek for GPU access with Pytorch
torch.cuda.is_available() # cuda is nvidia programming interface that allow to acess gpu for numerical computation


False

In [44]:
 # Setup device agnostic code
 device = "cuda" if torch.cuda.is_available() else cpu
 device


'cuda'

In [45]:
# count no. of gpu
torch.cuda.device_count()

1

### 3. Putting tensor (and models) on the GPU

The reason we want out tensor/models on the GPU is because using a GPU results in faster computations.

In [3]:
  # Create a tensor (default on the CPU)
  tensor = torch.tensor([1,2,3], device="cpu")


  #Tensor not on GPU
  print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
device = "cuda" if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [7]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

#### 4. Moving tensors back to CPU


In [9]:
# if tensor is on GPU, can't transform it to Numpy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])