In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#scaler using
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
#get scaler back as python int
scaler.item()

7

In [5]:
#vector
vector=torch.tensor([7,6])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random tensors
Why random  tensors?

Random tensors are important because the way many neural network learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random numbers -> look at data ->update random numbers

In [23]:
# create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6869, 0.8688, 0.3310, 0.8544],
        [0.0356, 0.6337, 0.1156, 0.0318],
        [0.6372, 0.1647, 0.8494, 0.9548]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor.shape

torch.Size([3, 4])

In [29]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,color channel(R,G,B)
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zero and Ones

In [31]:
#Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
#Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [41]:
# Use torch.arange()
one_to_ten=torch.arange(0,10,2)

In [43]:
#Creating tensors like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor datatypes

**Note** Tensor datatypes is one of the 3 big errors you'll run into pytorch & deep learning:

1. Tensors not right datatype 
2. Tensors not right shape
3. Tensors not on the right device

In [55]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None #torch.float16 #What datatype is the tensor (e.g float32 or float16)
                                        ,device=None  #What device is your tensor on
                                        ,requires_grad=False) #wheter or not to track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [56]:
float_32_tensor.dtype

torch.float32

In [57]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# Getting information from tensors

1. Tensors not right datatype -to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape    -to get shape from tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [58]:
#create tensor
some_tensor=torch.rand(size=(3,4))
some_tensor


tensor([[0.4513, 0.6212, 0.9585, 0.2342],
        [0.8503, 0.3172, 0.4248, 0.2941],
        [0.1833, 0.2320, 0.5617, 0.8863]])

In [63]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor:{some_tensor.shape}')
print(f'tensor is on {some_tensor.device}')

tensor([[0.4513, 0.6212, 0.9585, 0.2342],
        [0.8503, 0.3172, 0.4248, 0.2941],
        [0.1833, 0.2320, 0.5617, 0.8863]])
Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
tensor is on cpu


### Manipulating Tensors (tensor operations)
Tensor operation include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [69]:
# create a tensor
tensor=torch.tensor([1,2,3])
tensor=tensor+10
tensor

tensor([11, 12, 13])

In [71]:
# Multiply tensor by 10
tensor=tensor*10
tensor

tensor([110, 120, 130])

In [72]:
# subtract 10
tensor-10

tensor([100, 110, 120])

In [ ]:
# 2:15