In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#scaler using
scaler=torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
#get scaler back as python int
scaler.item()

7

In [6]:
#vector
vector=torch.tensor([7,6])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random tensors
Why random  tensors?

Random tensors are important because the way many neural network learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random numbers -> look at data ->update random numbers

In [16]:
# create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1579, 0.6058, 0.2497, 0.0962],
        [0.9156, 0.1950, 0.5847, 0.3453],
        [0.7957, 0.3825, 0.1173, 0.7951]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,color channel(R,G,B)
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zero and Ones

In [20]:
#Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten=torch.arange(0,10,2)

In [24]:
#Creating tensors like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor datatypes

**Note** Tensor datatypes is one of the 3 big errors you'll run into pytorch & deep learning:

1. Tensors not right datatype 
2. Tensors not right shape
3. Tensors not on the right device

In [25]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None #torch.float16 #What datatype is the tensor (e.g float32 or float16)
                                        ,device=None  #What device is your tensor on
                                        ,requires_grad=False) #wheter or not to track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# Getting information from tensors

1. Tensors not right datatype -to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape    -to get shape from tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [28]:
#create tensor
some_tensor=torch.rand(size=(3,4))
some_tensor


tensor([[0.5223, 0.5228, 0.9282, 0.7850],
        [0.1362, 0.2500, 0.8340, 0.1990],
        [0.5017, 0.4564, 0.2986, 0.5440]])

In [29]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor:{some_tensor.shape}')
print(f'tensor is on {some_tensor.device}')

tensor([[0.5223, 0.5228, 0.9282, 0.7850],
        [0.1362, 0.2500, 0.8340, 0.1990],
        [0.5017, 0.4564, 0.2986, 0.5440]])
Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
tensor is on cpu


### Manipulating Tensors (tensor operations)
Tensor operation include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [30]:
# create a tensor
tensor=torch.tensor([1,2,3])
tensor=tensor+10
tensor

tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor=tensor*10
tensor

tensor([110, 120, 130])

In [32]:
# subtract 10
tensor-10

tensor([100, 110, 120])

In [37]:
#Try out pytorch in built function
torch.mul(tensor,10)
tensor
torch.add(tensor,2)
tensor=tensor/10
tensor

tensor([11., 12., 13.])

## Matrix multiplication

1. Element -wise multiplication
2. Matrix multiplication (dot product)

There are two main rules to perform matrix multiplication
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimension**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [39]:
# Element wise multiplication
print(tensor, '*',tensor)
print(f'Equal to {tensor*tensor}')

tensor([11., 12., 13.]) * tensor([11., 12., 13.])
Equal to tensor([121., 144., 169.])


In [38]:
#Matrix multiplication faster
torch.matmul(tensor,tensor)

tensor(434.)

One of the most common error in deep learning :shape

In [40]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,8],
                       [8,11],
                       [9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [41]:
tensor.shape,  tensor_B.shape

(torch.Size([3]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a  **transpose**.

A **transpose** switches the axes or dimensions of given tensor.

In [42]:
tensor_B ,tensor_B.T

(tensor([[ 7,  8],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [ 8, 11, 12]]))

In [43]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### Finding the min, max , mean sum etc (tensor aggregation)

In [44]:
#create tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
#Find the min
torch.min(x)
x.mean() #same

tensor(45.)

In [59]:
# Finding max
torch.max(x)
x.max() #same

tensor(90.)

In [60]:
x.dtype
x=x.type(torch.float32)
torch.mean(x) #same
x.mean()

tensor(45.)

In [61]:
#find the sum
x.sum()

tensor(450.)

### Finding the position of min and max

In [62]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [63]:
# return position of min tensor
x.argmin() 

tensor(0)

In [65]:
# return position of max tensor
x.argmax()

tensor(9)

In [66]:
x[9]

tensor(90.)

In [ ]:
# 2.58